name: Publish package on Pypi

on:
  release:
    types: [published]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install -U twine
      - name: Build package
        run: |
          cd mpr_sbi_tvb
          python setup.py sdist
          python setup.py bdist_wheel
      - name: Release on Pypi
        env:
          TWINE_USERNAME: ${{ secrets.PYPI_USERNAME }}
          TWINE_PASSWORD: ${{ secrets.PYPI_PASS }}
        run: |
          echo "Publishing on pypi..."
          echo "Please uncomment the line below when the package is ready for release!"
#          twine upload dist/*
          rm -R dist
          rm -R build